### PR TITLE
Replace example project with newer version

### PR DESCRIPTION
**Pull request by m-haisham**
# Description

A replacement of the example project with a newer version as it was outdated

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Self-Code Review
- [x] Tested on example project

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Changed the example project to contain the new feature (only if applies)

### CODE REVIEW

**Comment by ciriousjoker** [comment]
@m-haisham It looks like you used the automatic migration tool provided by Flutter? If you did anything on top of that, please  explain that.

**Comment by m-haisham** [comment]
I deleted and recreated the whole example folder with `flutter create example`. Then added `flutter_lints` and applied all fixes and suggestions that it provided. I replaced the deprecated (textTheme) properties with suggestions and lastly removed the stack and gave the background color to scaffold widget itself.

**Review by ciriousjoker — APPROVED** [review]
lgtm

**Comment by ciriousjoker** [comment]
@m-haisham Sorry for not getting around to reviewing this sooner. Thanks for your contribution!

**Pull request merged**
