### PR TITLE
Added controller. hint() to trigger UI hint

### LINKED ISSUE #32: [Feature request] Programmatically trigger a hint that the card can be flipped
What I'm looking for is this:

```dart
FlipCardController controller;

// Flips to 30 degree before bouncing back to indicate that the card can be flipped by clicking/tapping on it
controller.hintFlip(30);
```

I'll fork this repo to implement this change, do you want me to create a PR for it?

### PR DESCRIPTION
**Pull request by ciriousjoker**
Fixes #32 

- Version bumped to 0.5.0

### Usage

 ```dart
 FlipCardController _controller = FlipCardController();
  
  _controller.hint(
    // optional
    duration: Duration(milliseconds: 400),
    // optional
    total: Duration(milliseconds: 900),
  );
  
  FlipCard(
    direction: FlipDirection.HORIZONTAL,
    controller: _controller,
    onFlip: () {
      //
    },
    back: Center(
      child: Container(
        child: ProjectFrontWidget(
          project: widget.project,
        ),
      ),
    ),
    front: Container(
      color: Colors.red,
      child: Center(
        child: ProjectBackWidget(
          project: widget.project,
        ),
      ),
    ),
  );
```

The duration will only run if not flipped yet and not already animating.
Animation runs for `duration` and reverses afterwards. The `total` duration will be used for this animation only and resets afterwards.

### CODE REVIEW

**Comment by ciriousjoker** [comment]
Actually, don't merge this just yet, I'll clean up the syntax and expose the controller as well to allow more control from outside.

**Comment by ciriousjoker** [comment]
Even if GlobalKeys are possible, Controllers are preferred. The controller that's introduced by this PR also provides the ability to access widget state if required.

This can be merged if you want, it's stable now.

**Comment by ciriousjoker** [comment]
@fedeoo Could you please merge this?

**Comment by ciriousjoker** [comment]
0.5.1 solves a use case where the card is aligned to the top (which can't be changed from outside this package)

**Comment by feibyte** [comment]
Merged in this PR. https://github.com/fedeoo/flip_card/pull/39
I'm closing this one. Thanks for your work.
I hope @BrunoJurkovic  or you can help to maintain this repo as I am not working with flutter now.

**Pull request closed without merging**
