### PR TITLE
Null safety, controller migration

### PR DESCRIPTION
**Pull request by BrunoJurkovic**
Hello there, this is my implementation of null safety, while also importing all of the code
from @CiriousJoker, here is how he described his implementation of the controller.

**Usage**
```dart
FlipCardController _controller = FlipCardController();
 
 _controller.hint(
   // optional
   duration: Duration(milliseconds: 400),
   // optional
   total: Duration(milliseconds: 900),
 );
 
 FlipCard(
   direction: FlipDirection.HORIZONTAL,
   controller: _controller,
   onFlip: () {
     //
   },
   back: Center(
     child: Container(
       child: ProjectFrontWidget(
         project: widget.project,
       ),
     ),
   ),
   front: Container(
     color: Colors.red,
     child: Center(
       child: ProjectBackWidget(
         project: widget.project,
       ),
     ),
   ),
 );
```
The duration will only run if not flipped yet and not already animating.
Animation runs for the duration and reverses afterward. The total duration will be used for this animation only and resets afterward.

### CODE REVIEW

**Review by feibyte — COMMENTED** [review]
Thanks @BrunoJurkovic  It looks great.
Just one thing I don't quite understand the purpose of the controller. Could you pls shed more light on it?
Sorry for the later reply as I'm not working with Flutter currently. Just wondering if you're keen to maintain this repo.

**Comment by feibyte** [comment]
I think I know that controller.

**Comment by BrunoJurkovic** [comment]
Thank you for merging this! Could you also publish it to pub.dev?

**Comment by feibyte** [comment]
Done. 
BTW,  Are you happy to maintain this lib? If so, I'm inviting you as an uploader in `pub.dev`.

**Comment by BrunoJurkovic** [comment]
> Done. 
> BTW,  Are you happy to maintain this lib? If so, I'm inviting you as an uploader in `pub.dev`.

Yes! I'd be very happy!

**Pull request merged**
