### PR TITLE
Only dispatch pointer events to active side

### LINKED ISSUE #1: Stacked Widgets cause issues
Hi @fedeoo,

I have the problem that interactable widgets like buttons are available (even tough invisible) on the backside of the card. I think thats because you use a stack to store both sides of a card. 

A good approach to that problem would be maybe conditional rendering of front and back side.

### PR DESCRIPTION
**Pull request by simolus3**
Absorb pointer events that would reach the inactive side of a flipped card.

Fixes #1

### CODE REVIEW

**Review by feibyte — APPROVED** [review]
It looks great!  
Also, I am looking for a new way to flip card.

**Comment by feibyte** [comment]
Thanks for your contribution. Recently  I was not working on this project. 
I apologized for that.   And I'd like to invite a new contributor in case I am not able to make it on time.
Not sure you're interested in it.

**Comment by simolus3** [comment]
Sure I'm interested :) I have some ideas to fix the "Localized Gesture Detection" issue, which I could work on.

**Comment by feibyte** [comment]
Thanks a lot.  
I think twice. It might not very good to absorb the event. If the user does need to catch that event, they could wrap their own component into AbsorbPointer. Is that right? What do you think?
I think it's pretty good to show the user they could implement they want by this way.

**Comment by simolus3** [comment]
I see, but the user can't know which side is active at a time because that information is not exposed: There is no way to know whether the front or back side of the card is visible, put the `AbsorbPointer` should only be enabled for the inactive side.
Also, I can't think of a use-case where you would not want a `AbsorbPointer`, I would always expect that invisible elements don't react to touches. Maybe we can introduce a `blockBackgroundTouches` parameter to the flip card widget so that the user can configure that behavior without having to write a lot of extra code?

**Comment by feibyte** [comment]
But I saw we set `absorbing` for the front side. Anything I missed?
Some users are asking if it's possible to click a button instead of clicking who side to trigger flip.

**Comment by simolus3** [comment]
I'm not sure if I understand you correctly, but we use an internal state of the `FlipCard` widget to determine whether `absorbing` needs to be set for a side. This information can't be accessed by other widgets (yet).
But I think I have a nice solution to only make the card flip when a specific button is pressed, I'll open a Pull Request for that tomorrow.

**Comment by feibyte** [comment]
You're right. I was wrong.  Even the Card was turned to 90 deg, it still captures the event.

**Pull request merged**
