### PR TITLE
Removed unused file which blocked null safety

### PR DESCRIPTION
**Pull request by ciriousjoker**
For some reason, a previous commit renamed the controller file without deleting the old one. This triggered the null-safety check to fail even though the package was already ready for sound null safety.

### CODE REVIEW

**Comment by ciriousjoker** [comment]
@fedeoo Can you please release a new package version after this? Google suggests using v1.0.0 or v0.6.0 to indicate the release of nullsafety, I'd go with v1.0.0. The package is relatively stable already with no upcoming breaking changes. I think the only realistic changes will be additional backwards compatible customization options.

**Review by feibyte — APPROVED** [review]

**Comment by feibyte** [comment]
Hi, @BrunoJurkovic  Would you like to take over this repo as I'm not working on Flutter repo any longer. 
If so, I can transfer this repo to you.

**Comment by BrunoJurkovic** [comment]
Yes, I would gladly have it

**Comment by BrunoJurkovic** [comment]
Sure @fedeoo I would love to maintain this repo!

**Comment by feibyte** [comment]
> Sure @fedeoo I would love to maintain this repo!
Thanks! I've invited you as an uploader in `pub.dev`, then it can be transferred.

**Comment by feibyte** [comment]
> Sure @fedeoo I would love to maintain this repo!

Failed to transfer GitHub repo as it showed `BrunoJurkovic/flip_card` already exist.

**Comment by BrunoJurkovic** [comment]
Try again, deleted the old repository @fedeoo

**Pull request merged**
